### ISSUE TITLE
Find a good name

### ISSUE THREAD

**Issue by pith** [seedstack/shed#1]
@seedstack/addons  @seedstack/friends This new repository is aimed to be a "SeedStack Guava", so we are looking for a better name than "utils".

Comment with your propositions (one proposition by comment) and vote with the new Gihub's "like" feature.

May the best win ! :trophy:

**Comment by pith** [comment]
**Shed**: _a simple roofed structure used for garden storage, to shelter animals, or as a workshop_
![image](https://cloud.githubusercontent.com/assets/2495124/14044789/9218dfa2-f294-11e5-8a3a-03088b3ddb55.png)

**Comment by ejemba** [comment]
**Toolbox** : Hu Hu ^^ (petit clin d'oeil , comprenne qui pourra)

**Comment by adrienlauer** [comment]
Go for shed!

**Comment by ydautremay** [comment]
Shed is great !
