### ISSUE TITLE
Bad Parent Pom in 1.0.0 released pom

### ISSUE THREAD

**Issue by ejemba** [seedstack/shed#2]
https://repo1.maven.org/maven2/org/seedstack/shed/shed/1.0.0/shed-1.0.0.pom

We can see that the parent of the 1.0.0 on maven central is actually a SNAPSHOT

```
<parent>
   <groupId>org.seedstack.poms</groupId>
   <artifactId>parent-internal</artifactId>
<version>3.0.0-SNAPSHOT</version></parent>
```
this prevents the start of a single application in brand new seedstack 16.11

**Comment by adrienlauer** [comment]
Fixed in 1.0.1 (distribution on its way)
